Web/AspNetCoreTemplate.Web/Controllers/Posts/PostsController.cs
namespace AspNetCoreTemplate.Web.Controllers.Posts
{
    using System.Linq;
    using System.Threading.Tasks;
    using AspNetCoreTemplate.Data.Models;
    using AspNetCoreTemplate.Services.Data;
    using AspNetCoreTemplate.Web.ViewModels.Posts;
    using javax.jws;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class PostsController : BaseController
    {
        private readonly IPostsService postsService;
        private readonly ICategoriesService categoriesService;
        private readonly UserManager<ApplicationUser> userManager;

        public PostsController(
            IPostsService postsService,
            ICategoriesService categoriesService,
            UserManager<ApplicationUser> userManager
            )
        {
            this.postsService = postsService;
            this.categoriesService = categoriesService;
            this.userManager = userManager;
        }

        public IActionResult ById(int id)
        {
            var postViewModel = this.postsService.GetById<PostViewModel>(id);
            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }

        [Authorize]
        public IActionResult Create()
        {
            var categories = this.categoriesService.GetAll<CategoryDropDownViewModel>();
            var vm = new CreatePostViewModel
            {
                Categories = categories,
            };

            return this.View(vm);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel input)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var postId = await this.postsService.CreateAsync(input.Title, input.Description, input.ImageURL, input.CategoryId, user.Id);

            return this.View("/Index");
        }

        public async Task<IActionResult> Like(ListPostsViewModel inputViewModel)
        {
            var postId = inputViewModel.Posts.Select(x => x.Id).FirstOrDefault();
            await this.postsService.Like(postId);

            return this.View("/Index");
        }

        public IActionResult Trending()
        {
            var posts = this.postsService.GetTrending();

            var viewModel = new ListPostsViewModel
            {
                Posts = posts,
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Delete(PostViewModel vm)
        {
            var postId = this.postsService.GetAll().Where(x => x.Id == vm.Id).FirstOrDefault();

            await this.postsService.Delete(postId.Id);

            return this.View("/Index");
        }
    }
}

Web/AspNetCoreTemplate.Web/Controllers/Users/UsersController.cs
namespace AspNetCoreTemplate.Web.Controllers
{
    using System.Threading.Tasks;

    using AspNetCoreTemplate.Data.Models;
    using AspNetCoreTemplate.Services.Data;
    using AspNetCoreTemplate.Web.ViewModels.Users;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(
            IUsersService usersService,
            UserManager<ApplicationUser> userManager
            )
        {
            this.usersService = usersService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> MyProfile()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var topPost =  this.usersService.GetTopPost(user.Id);

            var vm = new MyProfileViewModel
            {
                Image = "http://static.guim.co.uk/sys-images/Lifeandhealth/Pix/pictures/2009/3/3/1236074833250/Angry-man-001.jpg",
                Username = user.UserName,
                TopPost = topPost,
            };

            return this.View(vm);
        }

        public async Task<IActionResult> MyTopPosts()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var posts = this.usersService.GetMostLikedPosts(user.Id);

            var viewModel = new UserMostLikedPostsViewModel
            {
                Posts = posts,
            };

            return this.View(viewModel);
        }
    }
}

Web/AspNetCoreTemplate.Web/Views/Shared/_Layout.cshtml
@using AspNetCoreTemplate.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/fontawesome/css/all.css" rel=" stylesheet"/>
</head>
<body>
    <partial name="_Navbar" />

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <footer>
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @this.RenderSection("Scripts", required: false)
</body>
</html>

Web/AspNetCoreTemplate.Web/Views/Shared/_Navbar.cshtml
@using AspNetCoreTemplate.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="~/css/navbar.css" />
<!------ Include the above in your HEAD tag ---------->

<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Zorum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    @if (!this.SignInManager.IsSignedIn(this.User))
    {
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">
                    <i class="fa fa-home"></i>
                    Register
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">
                    <i class="fa fa-home"></i>
                    Login
                </a>
            </li>
        </ul>
    }
    else
    {
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">
                        <i class="fa fa-home"></i>
                        Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav ">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Posts" asp-action="Trending">
                        <i class="fas fa-fire-alt" style="color:red"></i>
                        Trending
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        <i class="far fa-list-alt" style="color:cyan"></i>
                        All
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Posts" asp-action="Create">
                        <i class="far fa-edit" style="color:whitesmoke"></i>
                        Create
                    </a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Users" asp-action="MyProfile">
                        <i class="far fa-edit" style="color:whitesmoke"></i>
                        MyProfile
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="/User/Logout">
                        <i class="fas fa-sign-out-alt" style="color:aliceblue"></i>
                        Logout
                    </a>
                </li>
            </ul>

        </div>
    }

</nav>